import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "./components/Header";
import Footer from "./components/Footer";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BarberiaJS",
  description: "Generated by create next app",
  icons:{
    icon: "../logos/GS_logo_blanco.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <Header/>
          <main>
            {children}
          </main>
          <Footer/>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
      </body>      
    </html>
  );
}
